# Generated by Django 6.0.2 on 2026-02-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
